# -*- coding: utf-8 -*-
"""cie-4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oVfVTVjIV9L2c6QVB_1IU5uNxMRxfKWH
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
data=pd.read_csv('/content/Mall_Customers.csv11.csv')
data.head()
data.info()
data.describe()
data.isnull().sum()

x=data.iloc[:,[3,4]].values

wcss_list=[]
for i in range(1,11):
  kmeans=KMeans(n_clusters=i,init='k-means++',random_state=42)
  kmeans.fit(x)
  wcss_list.append(kmeans.inertia_)
plt.plot(range(1,11),wcss_list)
plt.title('Elbow Method')
plt.xlabel('Number of Clusters')
plt.ylabel('WCSS_list')
plt.show()

optimal_cluster=5
kmeans=KMeans(n_clusters=5,init='k-means++',random_state=42)
y_predict=kmeans.fit_predict(x)

plt.scatter(x[y_predict==0,0],x[y_predict==0,1],s=100,c='blue',label='Cluster1')
plt.scatter(x[y_predict==1,0],x[y_predict==1,1],s=100,c='red',label='Cluster2')
plt.scatter(x[y_predict==2,0],x[y_predict==2,1],s=100,c='pink',label='Cluster3')
plt.scatter(x[y_predict==3,0],x[y_predict==3,1],s=100,c='cyan',label='Cluster4')
plt.scatter(x[y_predict==4,0],x[y_predict==4,1],s=100,c='black',label='Cluster5')
plt.scatter(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1],s=300,c='yellow',label='Centroids')
plt.title('Clusters of Customers')
plt.xlabel('Annual Income')
plt.ylabel('Spending Score')
plt.legend()
plt.show()